site_name: Intro to Marine Energy
docs_dir: src
repo_name: Intro to Marine Energy
repo_url: https://github.com/HMEC-UH/short_course_intro_2026

nav:
  - Welcome: index.md
  - Mesh Generation:
    - Overview: Gmsh/index.md
    - Gmsh: Gmsh/gmsh.md
  - Hydrodynamic Coefficients:
    - Overview: Capytaine/index.md
    - Meshmagick: Capytaine/meshmagick.md
    - Capytaine: Capytaine/capytaine.md
    - Example 1 - Spar Buoy: Capytaine/spar_buoy.md
    - Example 2- Heave Plate: Capytaine/heave_plate.md
    - Example 3- Two Body: Capytaine/two_body.md
  - Multibody:
    - Overview: WECSim/index.md
    - WEC-Sim: WECSim/wecsim.md

theme:
  name: material
  logo: assets/images/white_64.png
  favicon: assets/images/green_64.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: HMEC
  features:
    - navigation.tracking  # Updates URL bar dynamically as you scroll
    - navigation.indexes   # Allows folder titles to be clickable pages

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details # Optional: for collapsible blocks
  - pymdownx.superfences # Optional: for code blocks inside admonitions
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/alignments.css
  - stylesheets/color_scheme.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-svg.js

plugins:
  - search
  - privacy:
      links_attr_map:
        target: _blank
        rel: noopener noreferrer