site_name: Intro to Marine Energy
docs_dir: src
repo_name: Intro to Marine Energy
repo_url: https://github.com/HMEC-UH/short_course_intro_2026

nav:
  - Welcome: index.md
  - Getting Started:
    - Overview: environment/index.md
    - Python Setup: environment/python.md
    - MATLAB Setup: environment/matlab.md
  - Mesh Generation:
    - Overview: mesh/index.md
    - Gmsh: mesh/gmsh.md
  - Hydrodynamic Coefficients:
    - Capytaine: coeffs/capytaine.md
  - Multibody:
    - WEC-Sim: dynamics/wecsim.md

theme:
  name: material
  features:
    - navigation.tracking  # Updates URL bar dynamically as you scroll
    - navigation.indexes   # Allows folder titles to be clickable pages

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details # Optional: for collapsible blocks
  - pymdownx.superfences # Optional: for code blocks inside admonitions
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span

extra_css:
  - stylesheets/alignments.css
